# -*- coding: utf-8 -*-
"""Proyecto_programacion_11_11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zwokti3C3IGWJakCdHNU9Bel67LQhyMW
"""

import pandas as pd
!wget http://server01.labs.org.pe:2005/TB_CENTRO_VACUNACION.csv
pd.read_csv("TB_CENTRO_VACUNACION.csv")