# -*- coding: utf-8 -*-
"""Prueba_Fernando.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Npxq1KeHkeniGlg0ptGHmSS7X_YSvV69
"""

#$ pip install streamlit --upgrade
import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import urllib.request
import base64